# Server HTTP listen address
addr = "127.0.0.1:11000"

# Data store path
data_dir = "./var"

# Log path, if empty, stdout will be used
log_dir = 

# Server ID, must be unique in cluster
server_id = 1

# cluster, format is ID:host:port, host:port is for raft communication.
cluster = ["1:127.0.0.1:12000"]

# Cluster state, new or existing
# after service starts, we will save the current cluster in a config file.
# if new, we will use above cluster config as the new raft cluster.
# if existing, we will use before saved cluster config + above cluster as the raft cluster.
cluster_state = "existing"