# Server HTTP listen address
addr = "127.0.0.1:11000"

# Data store path
data_dir = "./var"

# Log path, if empty, stdout will be used
log_dir = ""

# Raft listen address
raft_addr = "127.0.0.1:12000"

# Raft cluster, if we have multi raft servers, write it here. It can contain above raft_addr
cluster = ["127.0.0.1:12000"]

# Raft cluster state, new or existing
# after service starts, we will save the current cluster in a config file.
# if new, we will use above cluster config as the new raft cluster.
# if existing, we will use before saved cluster config + above cluster as the raft cluster.
cluster_state = "existing"

# Monitored masters
masters = ["127.0.0.1:6379"]

# Monitored masters state, new or exising, the state explanation is the same as above cluser_state
masters_state = "existing"